# Generated by Django 2.1 on 2019-11-18 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Background Image')),
                ('name', models.CharField(default=None, max_length=100, verbose_name='Full Name')),
                ('about_desc', models.CharField(max_length=100, verbose_name='About Description')),
                ('email', models.EmailField(default=None, error_messages={'required': 'Please provide your email address.', 'unique': 'An account with this email exist.'}, max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile Number')),
                ('about_cont', models.TextField(verbose_name='About Content')),
                ('HTML5', models.CharField(blank=True, max_length=3, null=True, verbose_name='HTML5')),
                ('CSS3', models.CharField(blank=True, max_length=3, null=True, verbose_name='CSS3')),
                ('PYTHON', models.CharField(blank=True, max_length=3, null=True, verbose_name='PHYHON')),
                ('GIT', models.CharField(blank=True, max_length=3, null=True, verbose_name='GIT')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_for_blog', models.FileField(blank=True, null=True, upload_to='uploads/Author_img')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Blog Images')),
                ('blog_desc', models.CharField(max_length=200, verbose_name='Blog Description')),
                ('author_image', models.FileField(blank=True, null=True, upload_to='uploads/Author_img')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('blog_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Blog Author')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=150, verbose_name='Subject')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Background Image')),
                ('name', models.CharField(default=None, max_length=100, verbose_name='Profile Name')),
                ('home_desc', models.CharField(max_length=200, verbose_name='Home Description')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Portfolio Image')),
                ('portfolio_title', models.CharField(max_length=100, verbose_name='Portfolio Title')),
                ('portfolio_desc', models.TextField(verbose_name='Portfolio Description')),
                ('last_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_title', models.CharField(default=None, max_length=100, verbose_name='Qualification Description')),
                ('qualification_desc', models.TextField(verbose_name='Qualification Content')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend_app.Category'),
        ),
    ]
