# Generated by Django 2.1 on 2019-11-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marquee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
            ],
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_for_blog',
            field=models.FileField(blank=True, null=True, upload_to='uploads/Banner'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author_image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/Blog'),
        ),
    ]
