# Generated by Django 2.1 on 2019-11-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_app', '0002_auto_20191119_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_description',
            field=models.CharField(default='', max_length=300, verbose_name='Banner Description'),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_title',
            field=models.CharField(default='', max_length=250, verbose_name='Banner Title'),
        ),
    ]
