# Generated by Django 2.1 on 2019-12-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_app', '0003_auto_20191119_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_img',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to=None, verbose_name='Background Image', width_field=100),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_for_blog',
            field=models.ImageField(blank=True, height_field=50, max_length=200, null=True, upload_to=None, verbose_name='Blog Author', width_field=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author_image',
            field=models.ImageField(blank=True, height_field=50, null=True, upload_to=None, verbose_name='Blog Author', width_field=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_img',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to=None, verbose_name='Blog Images', width_field=50),
        ),
        migrations.AlterField(
            model_name='home',
            name='background_img',
            field=models.ImageField(blank=True, height_field=350, null=True, upload_to=None, verbose_name='Background Image', width_field=300),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_img',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to=None, verbose_name='Portfolio Image', width_field=50),
        ),
    ]
