# Generated by Django 2.1 on 2019-12-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_app', '0004_auto_20191213_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Background Image'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_for_blog',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Author Image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Blog Image'),
        ),
        migrations.AlterField(
            model_name='home',
            name='background_img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Background Image'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Portfolio Image'),
        ),
    ]
